### ISSUE TITLE
[FE] 프론트엔드 테스팅 셋업

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/store-6#10]
## :hammer: 기능 설명

React 에서 테스팅을 위한 셋업을 합니다.

https://ko.reactjs.org/docs/test-utils.html 참고해서 진행

테스팅은 블랙박스 테스팅 방식으로 인풋, 아웃풋에만 집중하면됨.

## 📑 완료 조건

- [ ] 필요 라이브러리 설치
- [ ] Jest, react-testing-library 사용해서 샘플 테스트 코드들 작성
- [ ] 샘플 테스트코드를 CI에서 테스트함.

## :thought_balloon: 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

FE기타 - 테스트 - 테스트코드 셋업

**Comment by peanut-lover** [comment]
저희 세팅 참조하시면 더 좋을듯하네요 .ㅎㅎ !!

> https://github.com/woowa-techcamp-2021/store-5/pull/7
