### ISSUE TITLE
1주차 팀간 리뷰 (부제: 5팀의 습격)

### ISSUE THREAD

**Issue by ondal1997** [woowa-techcamp-2021/store-6#11]
# 신어진

> 라우터 쪽 잘봤습니다.
>
> https://github.com/woowa-techcamp-2021/store-6/pull/9#pullrequestreview-729297519

# 고우혁

> 감탄만 있는 리뷰입니다.. :)
> 
> [#4](https://github.com/woowa-techcamp-2021/store-6/pull/4/files#r688274878)
> 
> [#4](https://github.com/woowa-techcamp-2021/store-6/pull/4/files#r688280419)
> 
> [#8](https://github.com/woowa-techcamp-2021/store-6/pull/8/files#r688282086)

# 손지호

>

# 권기석

>

**Comment by gomjellie** [comment]
![611637ED-EF3C-4B3F-83CB-A5F79683BB5D-7805-000006B3159FA9F6_file](https://user-images.githubusercontent.com/13645032/129332734-9b7dcae2-04a3-4f7e-b6cc-50bc14d4f47d.jpg)

너무 즐거운 습격이였습니다~
