### ISSUE TITLE
[BE] 인증 API 구현

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/store-6#13]
## :hammer: 기능 설명

로그인, Refresh API 등 JWT 관련 인증 API를 구현합니다.

## 📑 완료 조건

- [x] Oauth를 제외한 자체 로그인 정보를 사용해서 JWT 토큰을 발급받을 수 있는 API를 구현해야 합니다.
- [x] JWT 토큰은 Access 토큰, Refresh 토큰으로 나눠서 발급해야 합니다.
- [x] Refresh 토큰은 최대한 보안에 신경써야 합니다.
- [x] Refresh 토큰을 사용해서 AccessToken을 재발급할 수 있는 API를 구현해야 합니다.
- [x] 기한이 남은 Refresh 토큰이 있는 사용자라고 하더라도 서버 측에서 접근을 막을 수 있는 방법을 적용해야 합니다. 
- [x] 변경된 API는 API 문서에 업데이트를 해야 합니다.
- [x] 어떤 방식으로든 테스트가 진행되어야 합니다.

## :thought_balloon: 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

- [BE] 로그인 페이지 - API - 로그인/로그아웃 API
- [BE] 로그인 페이지 - API - Refresh 토큰을 사용한 Access 토큰 갱신 API

**Comment by hseoy** [comment]
redis promisify 오류 해결 : 
- [Error in redis client del function with typescript](https://stackoverflow.com/questions/62320989/error-in-redis-client-del-function-with-typescript)

**Comment by hseoy** [comment]
![인증 로직  001](https://user-images.githubusercontent.com/75124422/129442593-b856c399-10a2-4861-81b5-d9e8e5597435.jpeg)
![인증 로직  002](https://user-images.githubusercontent.com/75124422/129442596-6d6cf6c4-b73b-42c0-82be-382b449d7f77.jpeg)
![인증 로직  003](https://user-images.githubusercontent.com/75124422/129442598-9d790db7-5f00-428c-b287-8f8f2328be30.jpeg)

**Comment by jonghopark95** [comment]
인증로직 003의 2, 3에서 존재 여부보다는 유효 여부가 맞는 표현 아닐까요??
악의적인 refresh token을 넣어 요청했을 경우 존재 여부만 확인하면 안될 것 같습니다

**Comment by hseoy** [comment]
우리 서비스에서 발급했고 기한이 남아있는 완전히 유효한 Refresh Token이라 하여도 Redis에 Refresh Token이 없으면 유효하지 않는 것으로 처리하게 됩니다. Redis 사용 부분만 봤을 때는 Redis는 단지 DB이고 유효 여부를 판단하는 주체는 아니기 때문에 존재 여부를 확인한다라는 표현을 사용했습니다. 

Redis 사용 부분 외의 Token 검증 로직은 당연히 필요한 부분이라 생각하고 위 그림이 완전한 인증 로직보다 Redis를 사용한 인증로직에 대해서 설명하는 것이 주 목적이었어서 검증 로직에 대한 그림이 빠져있네요. 추가하도록 하겠습니다.

**Comment by hseoy** [comment]
그리고 한 가지 더 Redis를 사용하면서 얻은 장점이 우리 서비스에서 발급된 Refresh Token에 대해서만 Redis에 저장되고 Redis에 없는 Refresh Token은 전부 비유효하기 때문에 검증 로직이 없다고 해도 만료된 토큰 외에는 모두 걸러질 것 같습니ㅏㄷ.

**Comment by jonghopark95** [comment]
오오... 그렇군요 알겠습니다 👍

**Comment by hseoy** [comment]
> 우리 서비스에서 발급했고 기한이 남아있는 완전히 유효한 Refresh Token이라 하여도 Redis에 Refresh Token이 없으면 유효하지 않는 것으로 처리하게 됩니다. Redis 사용 부분만 봤을 때는 Redis는 단지 DB이고 유효 여부를 판단하는 주체는 아니기 때문에 존재 여부를 확인한다라는 표현을 사용했습니다.
> 
> Redis 사용 부분 외의 Token 검증 로직은 당연히 필요한 부분이라 생각하고 위 그림이 완전한 인증 로직보다 Redis를 사용한 인증로직에 대해서 설명하는 것이 주 목적이었어서 검증 로직에 대한 그림이 빠져있네요. 추가하도록 하겠습니다.

검증 로직 부분에 대해서 검토를 해봤는 데, 유효한 토큰이라는 정의를 1. 우리 서비스에서 발급된 토큰이다. 2. 만료되지 않았다라고 정의했을 때 Redis에 있는지 존재 여부만 체크해도 된다라는 결론을 얻었습니다. 

이러한 결론 아래에는 다음과 같은 전제를 바탕으로 했습니다.
1. Redis에 있는 Token 데이터는 토큰을 발행할 때 등록되므로 모두 우리 서비스에 있는 토큰이다.
2. Redis의 데이터를 등록할 때 만료시간을 Refresh 토큰의 기한과 같게 설정했기 때문에 Redis에 존재한 모든 Token은 만료되지 않은 토큰이다.
