### ISSUE TITLE
[FE] styled-components 1차 정벌

### ISSUE THREAD

**Issue by jonghopark95** [woowa-techcamp-2021/store-6#165]
## 📑 완료 조건

- [x]  tagged template으로 스타일을 추가할 수 있도록 처리해야 합니다.
- [ ]  props를 받도록 처리해야 합니다.
- [x]  CSS selector를 사용할 수 있어야 합니다.

## 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

[FE] Core - Styled Components

**Comment by gomjellie** [comment]
맛집 추천드립니다.

https://github.com/woowa-techcamp-2021/store-5/pull/70
https://github.com/woowa-techcamp-2021/store-5/pull/85
