### ISSUE TITLE
상품필수정보 누르면 가운데영역이 펼쳐지는데 무슨영역인지 모르겠습니다.

### ISSUE THREAD

**Issue by crongro** [woowa-techcamp-2021/store-6#206]
<img width="333" alt="배민문방구__상품_상세_페이지" src="https://user-images.githubusercontent.com/1456761/131074744-b661c178-8b99-4921-be9e-5d56259b370d.png">

제곧내

**Comment by jonghopark95** [comment]
해결했습니다 감사합니다 :)
