### ISSUE TITLE
아이템 리스트 => 상세페이지 후 뒤로가기했을 때 상태 저장 문제 

### ISSUE THREAD

**Issue by jjunyjjuny** [woowa-techcamp-2021/store-6#213]
## ⚠️ 버그 설명

보고싶은 순서로 상품보다가 뒤로왔을 때 필터가 최신순으로 돌아와있음. 
유지되면 좋을 거 같다. 
마찬가지로 카테고리도 뒤로가기시 저장되어 있지 않는 듯 함. 

**처음 웰컴페이지에서 선택한 카테고리로 고정되어 있다.**

## 📑 완료 조건

- [x] 상품 상세 페이지를 들어갈 경우에는 이전 상태를 유지시켜줘야 합니다.

## :thought_balloon: 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

- 에러 수정 - 상품 목록 페이지 - 아이템 리스트 상세 페이지 후 뒤로가기 했을 때 카테고리, 정렬 상태 저장

**Comment by jonghopark95** [comment]
답변 감사합니다 :)
다만, 내부 회의 결과 해당 이슈는 저희 기획과 맞지 않는 부분이라 close 하려고 합니다
조언 주셔서 너무 감사합니다 !

**Comment by gomjellie** [comment]
![R720x0 fjpg](https://user-images.githubusercontent.com/13645032/131250097-6800d58a-bced-42a2-b04e-ad29c08a9380.jpeg)

**Comment by hseoy** [comment]
라고 생각했지만 필요하다고 다시 느껴 ReOpen 합니다.
