### ISSUE TITLE
[BUG] 회원 가입 페이지 : 약관 관련 이슈

### ISSUE THREAD

**Issue by edegiil** [woowa-techcamp-2021/store-6#218]
## ⚠️ 버그 설명

회원가입시 약관 동의를 하나 해제해도 모두 동의는 체크가 되어 있습니다..

## 📑 완료 조건

![스크린샷 2021-08-27 오후 2 26 47](https://user-images.githubusercontent.com/35324795/131076416-9c8c037d-864f-412e-b9ff-37f9b2da1a54.png)

- [x] 약관 모두 동의 체크 되어 있을 경우 계속 체크 되어 있는 문제 지우기

**Comment by hseoy** [comment]
- #240 이슈에서 약관 관련 문제는 해결했습니다.
