### ISSUE TITLE
[BUG] 얘는 왜 떨어지다가 마나요...

### ISSUE THREAD

**Issue by edegiil** [woowa-techcamp-2021/store-6#221]
## ⚠️ 버그 설명

끝까지 안내려가서 불편하네요... ㅡㅡ

## 📑 완료 조건

![스크린샷 2021-08-27 오후 2 30 54](https://user-images.githubusercontent.com/35324795/131076781-5ce15055-fff5-4ba1-835f-68e5025c8be6.png)

**Comment by hseoy** [comment]
해결했습니다!!
