### ISSUE TITLE
[BUG] Oauth 계정으로 회원가입 오류

### ISSUE THREAD

**Issue by Seogeurim** [woowa-techcamp-2021/store-6#222]
## ⚠️ 버그 설명

구글 계정으로 회원가입 시 바로 로그인이 되지 않는 문제가 있습니다.

### 사용 브라우저

크롬

### 버그 발생 순서

1. 구글 계정으로 회원가입을 진행합니다.
2. 전화번호 입력, 약관 동의 후 회원가입 완료 버튼을 누릅니다.
3. [bug] 다시 구글 계정 선택 화면이 나옵니다.
4. 구글 계정 선택을 다시 합니다.
5. 메인 페이지로 리다이렉트됩니다.
6. 다시 아이템 리스트가 나오는 페이지로 들어갑니다.
7. [bug] 구글 로그인이 되어있지 않습니다.
8. 로그인을 다시 합니다.
9. 메인 페이지로 리다이렉트됩니다.
10. 이제야 프로필이 보입니다 !

## 📑 완료 조건

- [x] 구글 회원가입 성공 시 상품 목록 페이지로 이동시켜야 합니다.
- [x] 재로그인 시도시 유저 정보가 반영되어 있어야 합니다.

## :thought_balloon: 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

- 에러 수정 - 회원가입 페이지 - 구글 계정으로 회원가입 오류

**Comment by hseoy** [comment]
해결했습니다 :) 피드백 감사합니다 ㅎㅎㅎㅎ
