### ISSUE TITLE
사진 위의 흰 글씨가 잘 안보이는 것 같습니다.

### ISSUE THREAD

**Issue by sshrik** [woowa-techcamp-2021/store-6#223]
## :hammer: 사진 위의 흰 글씨가 잘 안보이는 것 같습니다.

사진 위의 흰 글씨가 잘 안보이는 것 같습니다.

현재는 이렇게 되어있습니다!
![image](https://user-images.githubusercontent.com/20200204/131076867-93377af8-b683-482f-bd8f-f755638067e8.png)

이런 느낌은 어떨까요? 뒤에 검은 투명한 걸 깔아서?
![image](https://user-images.githubusercontent.com/20200204/131076940-718831cd-7a45-4f47-aaa4-4eddae2afcf1.png)

## 📑 완료 조건

- [ ] 팀의 만족..?

## :thought_balloon: 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

**Comment by jonghopark95** [comment]
답변 감사합니다 :)
다만, 내부 회의 결과 해당 이슈는 저희 기획과 맞지 않는 부분이라 close 하려고 합니다
조언 주셔서 너무 감사합니다 !

**Comment by gomjellie** [comment]
![R720x0 fjpg](https://user-images.githubusercontent.com/13645032/131250097-6800d58a-bced-42a2-b04e-ad29c08a9380.jpeg)
