### ISSUE TITLE
[BUG] 라우터 오류 (좋아요 페이지 새로고침 시 메인으로 이동)

### ISSUE THREAD

**Issue by Seogeurim** [woowa-techcamp-2021/store-6#224]
## ⚠️ 버그 설명

아이템 리스트를 보다가 새로고침했을 때 메인 페이지(음성채팅 페이지)로 이동합니다.

변경
좋아요 페이지 새로고침 시 메인으로 이동

### 사용 브라우저

크롬

### 버그 발생 순서

1. 메인 페이지에서 스페이스키를 눌러 아이템 리스트 페이지로 이동합니다.
2. 마이페이지 이동 등 ~ 여러가지 작업을 합니다.
3. 새로고침 키를 누릅니다.
4. [bug] 메인페이지로 이동합니다.

변경
좋아요 페이지 새로고침 시 메인을 이동하는 문제로 해당 이슈 범위를 축소합니다.

### 추가적으로 

- 새로고침했을 때 사용자는 현재 페이지가 새로고침되는 것을 기대할텐데 메인페이지로 이동하여 다시 캐릭터를 이동하여 다시 스페이스키를 눌러 사이트에 접속하는 프로세스가 조금 무거운 것 같습니다.
- 페이지 가운데에 있는 '배민문방구' 버튼을 누르면 메인 페이지로 이동하는데, 이런 부분도 불편한 것 같습니다.

**Comment by hseoy** [comment]
해결되었습니다! 피드백 감사해요~~~ ㅎㅎ
