### ISSUE TITLE
[UX 개선사항] 정리

### ISSUE THREAD

**Issue by HobinLee** [woowa-techcamp-2021/store-6#228]
- [x] 전체적으로 반응이 느려서 경험이 좋지 않아요 ㅠㅠ
- [x] 계속 메인화면으로 가니까 불편합니다.
- [x] 무한스크롤시에 조금 빨리 내려도 동작하면 좋겠습니다..!
6팀 화이팅

**Comment by jonghopark95** [comment]
@HobinLee 해당 이슈는 #216 #257 로 분리해서 작업하겠습니다 
조언해주셔서 감사합니다 :)
