### ISSUE TITLE
[BE] 상품 업로드 api 막기

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/store-6#276]
## :hammer: 기능 설명

상품 업로드 api 막기

## 📑 완료 조건

- [ ] 상품 업로드 api 막기

**Comment by hseoy** [comment]
이거 처음 초기 개발할 때 사용했던 api 였죠? 배포할 때는 사용안되는

**Comment by hseoy** [comment]
그러면 환경변수에 따라 막는 것도 괜찮을 것 같아요. development일 때만 열어두도록?

**Comment by gomjellie** [comment]
이거 저희 상품목록넣을때 제 파이썬 스크립트로 넣으려고 병현님이 열어주신 api에요

**Comment by gomjellie** [comment]
```ts
if (process.env.NODE_ENV === 'development')
    productRouter.post('/', handleAddProduct);
```
이렇게 할까요?

**Comment by hseoy** [comment]
넵. 만들어놨는 데 아예 주석 처리하는 건 이상한 것 같고,,, 개발할 때 사용했다라는 의미가 그쪽이 더 드러나지 않을까요?

**Comment by gomjellie** [comment]
알겠습니다~ 저도 그게 좋을거같네요
