### ISSUE TITLE
[BE] API 명세 작성 (문서화)

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/store-6#5]
## :hammer: 기능 설명

API 명세를 작성합니다.

## 📑 완료 조건

- [x] wiki에 API 명세 문서가 올라가 있어야 합니다.
- [x] 각 명세에는 request 및 response에 대한 정의가 있어야 합니다. 

## :thought_balloon: 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

[BE] 기타 - API - API 명세 작성 (문서화)

**Comment by qudgus21** [comment]
[API 명세](https://github.com/woowa-techcamp-2021/store-6/wiki/API) 를 wiki에 업로드 하였습니다.
