### ISSUE TITLE
[BE] DB Schema 설계

### ISSUE THREAD

**Issue by qudgus21** [woowa-techcamp-2021/store-6#6]
## :hammer: 기능 설명

기능 설명

DB Schema 설계합니다.

## 📑 완료 조건

- [x] ERD 설계 후 위키에 올리기
- [x] ERD 설계 바탕으로 TypeORM Entity 작성하기

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 관계 작성에서 실수하지 않도록 조심조심....

## ❗ 선행되어야 할 이슈

> 먼저 작업해주어야 할 이슈를 태그해주세요.

- None

## :thought_balloon: 관련 Backlog

- [BE]기타 - DB - DB Schema 설계

## 🕰 예상 소요 시간

- 6h

**Comment by hseoy** [comment]
ERD 작성한 것 위키에 추가했습니다 ~ [Click](https://github.com/woowa-techcamp-2021/store-6/wiki/ERD)
