### ISSUE TITLE
[리팩토링] 초기 로딩 속도 개선을 위한 폰트 파일 및 스크립트 번들링 파일 용량 최적화

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/store-6#91]
## :hammer: 기능 설명

폰트 파일 등 파일의 크기를 줄이는 방법을 비롯한 여러 방법을 사용해 초기 로딩 속도를 개선합니다.

현재 폰트 사이즈 파일은 5mb가 넘는 데 woff/woff2 확장자 사용해서 최대한 사이즈를 줄여야 합니다.

제 개인 네트워크 상황(모바일 데이터, 한정된 속도) 기준 40초가 넘는 초기 로딩 속도가 소요됐습니다.

## 📑 완료 조건

- [x] 폰트 파일의 확장자를 OTF에서 WOFF, WOFF2로 변경해야 합니다.
- [x] app.js 번들링 파일의 용량을 최적화할 수 있는 방법을 적용해야 합니다.

## :thought_balloon: 관련 Backlog

> [대분류] - [중분류] - [Backlog 이름]

- 리팩토링 - 초기 로딩 속도 - 폰트 파일 용량 최적화
- 리팩토링 - 초기 로딩 속도 - app.js 번들링 파일 용량 최적화

**Comment by gomjellie** [comment]
![image](https://user-images.githubusercontent.com/13645032/130528414-eefc3638-a1b1-4b8e-88d5-40f84ae585a6.png)

웹팩은 답을 알고있었네요...

예전부터 워닝 뜨던걸 계속 무시하고있었어요

**Comment by hseoy** [comment]
[8월 25일부터 시작된 웹사이트 성능 최적화 여정](https://github.com/woowa-techcamp-2021/store-6/wiki/8%EC%9B%94-25%EC%9D%BC%EB%B6%80%ED%84%B0-%EC%8B%9C%EC%9E%91%EB%90%9C-%EC%9B%B9%EC%82%AC%EC%9D%B4%ED%8A%B8-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94-%EC%97%AC%EC%A0%95)
